### ISSUE TITLE
Provide AppImage for download

### ISSUE THREAD

**Issue by probonopd** [dmartingit/charter#1]
https://github.com/dmartingit/charter/blob/c61c0fdcb9ca35e5e01e5ce30cbc0fe3e429c3d7/package.json#L30

Please provide the AppImage for download on GitHub Releases, thanks.

**Comment by dengelgit** [comment]
Zipped folders are already in the release.

**Comment by probonopd** [comment]
Please do not zip AppImage files. Reason: https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages#common-mistake
